services:
  scriptify_frontend:
    build: .
    container_name: scriptify_frontend
    restart: always
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY:-}
    ports:
      - "3001:3000"
    networks:
      - web

networks:
  web:
    external: true
